# Generated by Django 4.1.2 on 2023-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=100)),
                ("sender", models.EmailField(max_length=254)),
                ("recipent", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
    ]
